name: ride_sharing_pro
description: A professional ride sharing app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  google_maps_flutter: ^2.14.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7  # ADD THIS
  webview_flutter: ^4.4.2
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/car_bg.png